# Generated by Django 2.1 on 2020-03-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_auto_20200317_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='userSex',
            field=models.CharField(default='男', max_length=6),
        ),
    ]
