# Generated by Django 2.1 on 2020-03-17 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0004_auto_20200317_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('orderId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('orderData', models.DateTimeField(auto_now=True)),
                ('orderMon', models.FloatField()),
                ('userInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.UserInfo')),
            ],
        ),
    ]
