# Generated by Django 2.1 on 2020-03-17 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0005_orderinfo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderinfo',
            table='order_table',
        ),
    ]
