# Generated by Django 2.1 on 2020-03-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0007_product_usergoods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergoods',
            name='pro',
        ),
        migrations.RemoveField(
            model_name='usergoods',
            name='user',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='pros',
            field=models.ManyToManyField(to='userApp.Product'),
        ),
        migrations.DeleteModel(
            name='UserGoods',
        ),
    ]
