# Generated by Django 2.1 on 2020-03-18 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userApp', '0008_auto_20200318_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('userInfo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userApp.UserInfo')),
            ],
        ),
    ]
